const practiceModes = [
     {
    id: "write",
    number: "1",
    title: "Luyện viết",
    description:
      "AI sẽ chấm và góp ý bài viết của bạn để cải thiện ngữ pháp và cách diễn đạt.",
    image: "/ThChi_Practice_Write.png",
    imageAlt: "Mèo luyện viết",
    buttonLabel: "Bắt đầu luyện viết",
    to: "/practice/write",
    theme: {
      cardBg: "#f0fdf4",
      cardBorder: "#bbf7d0",
      accent: "#22c55e",
      buttonBg: "transparent",
      buttonBorder: "#22c55e",
      buttonText: "#16a34a",
      bubbleBg: "#bbf7d0",
      numberColor: "#16a34a",
      titleColor: "#15803d",
    },
    comingSoon: false,
  },
  {
    id: "speak",
    number: "2",
    title: "Luyện nói",
    description:
      "Nói chuyện với AI và nhận phản hồi để phát âm tự nhiên và lưu loát hơn.",
    image: "/ThChi_Practice_Speak.png",
    imageAlt: "Mèo luyện nói",
    buttonLabel: "Bắt đầu luyện nói",
    to: "/practice/speak",
    theme: {
      cardBg: "#eff6ff",
      cardBorder: "#bfdbfe",
      accent: "#3b82f6",
      buttonBg: "transparent",
      buttonBorder: "#3b82f6",
      buttonText: "#1d4ed8",
      bubbleBg: "#bfdbfe",
      numberColor: "#1d4ed8",
      titleColor: "#1e40af",
    },
    comingSoon: false,
  },
  {
    id: "ai-chat",
    number: "3",
    title: "AI Quizlet",
    description:
      "AI sẽ tạo các cuộc hội thoại theo chủ đề giúp bạn ôn tập từ vựng và luyện phản xạ giao tiếp.",
    image: "/ThChi_Practice_AIQuizlet.png",
    imageAlt: "Hội thoại với AI",
    buttonLabel: "Bắt đầu trò chuyện",
    to: "/practice/ai-quizlet",
    theme: {
      cardBg: "#faf5ff",
      cardBorder: "#e9d5ff",
      accent: "#a855f7",
      buttonBg: "transparent",
      buttonBorder: "#a855f7",
      buttonText: "#7c3aed",
      bubbleBg: "#e9d5ff",
      numberColor: "#7c3aed",
      titleColor: "#6d28d9",
    },
    comingSoon: false,
  },
]
export default practiceModes